### PR TITLE
Pm1.3 team08

### PR DESCRIPTION
**Pull request by vincent-fugnitto**
refactored code based on comments, added rt client and bitbucket issues

### CODE REVIEW

**Comment by smokhov** [comment]
Thanks. @vincent-fugnitto do you have any project files that go with that like Eclipse, Makefile, or OpenESB's? Can simply commit those to the same branch and they would show up in this PR before it is merged.

Don't forget to tag your last commit in that branch per spec.

**Comment by smokhov** [comment]
Also, are you the sole answer of all these comments, @vincent-fugnitto ?

**Comment by vincent-fugnitto** [comment]
Hi, sorry I just saw your comments, yes I am mainly the sole answer to these comments. I can add the Eclipse project files if you like.

**Comment by smokhov** [comment]
Double typos of mine ... sole **author** of all these **commits** is what I meant. Yes, I require Eclipse project files, thanks @vincent-fugnitto

**Comment by smokhov** [comment]
Because if others have contributed, we need also proper authorship.

**Comment by smokhov** [comment]
I mean commit authors, not javadoc comments (though javadoc comments are also helpful). Where can I find their commits? If you tell me which user (name/email on GitHub, by commenting at each commit above), did mostly which commit in your commit history here, I can amend them later during the merge. Or you can amend them yourself if you know how to use `git ... --ammend ...`. Normally, you'd preserve their history with your own so they all get properly attributed commit authorship and shown in history.

**Comment by vincent-fugnitto** [comment]
I added the respected authors to the docstrings and I will push shortly with the project files. For the authors, you can see the other author's commit directly on our bitbucket account where I took and integrated the code, I hope this is alright. https://bitbucket.org/soen487-w18-08/soen487-w18-team08/commits/all

**Comment by smokhov** [comment]
Merged for now to local `team8` branch for post-processing and further merging with `team3` and the master. Will need to re-check TODOs.

**Comment by smokhov** [comment]
@qtdnguyen -- JFYI of what's coming

**Comment by vincent-fugnitto** [comment]
Sir, I'm confused on how we are to integrate with the other team, I have forked and created the upstream and fetched and I'm unsure on how to incorporate the changes from the other team without having both our branches merged to master

**Comment by smokhov** [comment]
@vincent-fugnitto -- wait a bit; I am working on a local clone to merge yours and other team's PRs now stored in my branches. After I am done, the merged copy to share will be in master. You rebase your forks from master after that.

**Comment by vincent-fugnitto** [comment]
@smokhov I understand that things are needed for both the teams to successfully implement the features of PM2.3, the only thing is my team and I are stressed that we will complete the deliverable on time since there will only be two days left in theory to complete all the features while we all have other work. Is this deliverable still due on Sunday? We had to wait for the requirements to be completed, as well as the PM2.1-2.2 this week, and now we have the repo itself to wait for, I just wanted to express our concerns as a team

**Comment by smokhov** [comment]
@vincent-fugnitto -- do not worry for this deadline at this time; better to have completed quality work than incomplete rushed deliverable

**Comment by smokhov** [comment]
@vincent-fugnitto -- merges are done, please sync and proceed (rebase from master)

**Comment by vincent-fugnitto** [comment]
@smokhov thank you for the updates to the repository. I know you mentioned earlier not to worry about the deadline but my teammates just want to confirm on when you expect all the code to be delivered? is it tonight at 12?

**Comment by daniilkarpov** [comment]
Hello @smokhov, it is unclear to us what kind of implementation needs to be created for "(c) Teams 3 and 8: Refactor rt/splints a-la fp/v11/splints. The main class would be RT with the API createIssue() and editIssue() from ISplints. There ought to be Config and Constants." From my understanding we need to create a REST post() method for this but RT already has a REST service: https://rt-wiki.bestpractical.com/wiki/REST#Ticket_Create. So do we call this REST service and our REST service acts as a wrapper of sorts? Thank you

**Comment by smokhov** [comment]
@vincent-fugnitto @daniilkarpov please move on with the discussion from the closed PR to unrelated topics either to Bitbucket or GitHub issues as appropriate. I'll answer there,

**Pull request merged**
